### PR TITLE
Make sliders more intuative

### PR DESCRIPTION
**Pull request by yustarandomname**
Sliders are now play buttons that are more intuitive. See changes here: https://deploy-preview-27--playful-otter-9e0500.netlify.app/applet/lines_and_planes/plane_line_intersection

image

### CODE REVIEW

**Comment by juliavdkris** [comment]
I think this is a cool change, but we should have an option to use the old sliders as well. Preferably with an argument that you can set per applet.

Because this does make the applet less "interactive" and more just an animation. I would imagine that in some cases, it's a lot better if the user can change the slider themselves.

**Review by PHengst — APPROVED** [review]
I love this change! This really lets every applet show off its interactivity. The only thing is that I find it a little finicky that you cant access the sliders without triggereing the animations.

**Comment by juliavdkris** [comment]
Beryl also mentioned yesterday that she would prefer if the sliders can still be changed manually when the animation is paused

I think maybe having multiple sliders with one small play button that animates all of the sliders at the same time could be a nice compromise? That way we keep the simplicity of a play button, while still having the more direct interactivity of sliders. But we'll probably discuss it tomorrow

**Comment by yustarandomname** [comment]
Topic to discuss for tomorrow... (I have opinions 😉)

**Comment by yustarandomname** [comment]
Pauline has opinions too 😉

**Comment by juliavdkris** [comment]
Opinions :popcorn:

**Pull request merged**
