### PR TITLE
Show axis labels on all numbers, not just even

### PR DESCRIPTION
**Pull request by juliavdkris**
Based on a request from Fokko ages ago, that we forgot about :p

Before:
image

After:
image

### CODE REVIEW

**Comment by yustarandomname** [comment]
Who would possibly write "indecator" in stead of "indicator" 🙃

**Comment by juliavdkris** [comment]
> Who would possibly write "indecator" in stead of "indicator" upside_down_face

No idea, someone with dyslexia perhaps? ¯\\\_(ツ)\_/¯

&nbsp;

Also: let's wait with merging till the next meeting, to check with Fokko

**Comment by juliavdkris** [comment]
nevermind lmao

**Comment by juliavdkris** [comment]
Hahah true, I just wanted to make sure this is what Fokko meant, but if not I can just make a new PR :p

**Pull request merged**
